name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag github-actions-image:$(date +%s)

    - name: os-type
      run: |
       uname -a
       cat /etc/os-release

    - name: conatainer-details
      run: |
       docker ps-a
       docker images
      
